name: PermissionsBukkit
main: com.platymuus.bukkit.permissions.PermissionsMain
author: The Bukkit Team
website: http://bukkit.org
version: 1.0
commands:
  permissions:
    aliases: perms
    description: Commands for manipulating permissions.
    usage: |
        /<command> reload - reload the configuration from disk.
        /<command> check <player> <node> - check if a player has a permission (any plugin).
        /<command> group - list group-related commands.
        /<command> group list - list all groups.
        /<command> group players <group> - list players in a group.
        /<command> group addperm <group> <node> - add a permission to a group.
        /<command> group removeperm <group> <node> - remove a permission from a group.
        /<command> player - list player-related commands.
        /<command> player groups <player> - list groups a player is in.
        /<command> player addgroup <player> - add a player to a group.
        /<command> player removegroup <player> - remove a player from a group.
        /<command> player addperm <player> <node> - add a permission to a player.
        /<command> player removeperm <player> <node> - remove a permission from a player.
permissions:
  permissions.*:
    children:
      permissions.help: true
      permissions.reload: true
      permissions.check: true
      permissions.group.*: true
      permissions.player.*: true
  permissions.group.*:
    children:
      permissions.group.help: true
      permissions.group.list: true
      permissions.group.players: true
      permissions.group.listparents: true
      permissions.group.addperm: true
      permissions.group.removeperm: true
  permissions.player.*:
    children:
      permissions.player.help: true
      permissions.player.groups: true
      permissions.player.addgroup: true
      permissions.player.removegroup: true
      permissions.player.addperm: true
      permissions.player.removeperm: true